# Generated by Django 4.1 on 2023-11-18 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="description",
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
