# Generated by Django 4.1 on 2023-11-29 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0003_resume_email_resume_first_name_resume_last_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="email",
            field=models.EmailField(default="", max_length=30),
        ),
        migrations.AlterField(
            model_name="resume",
            name="first_name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="resume",
            name="last_name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="resume",
            name="phone",
            field=models.CharField(default="", max_length=20),
        ),
    ]
