# Generated by Django 4.1 on 2023-11-29 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0004_alter_resume_email_alter_resume_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="email",
            field=models.EmailField(default="", max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="resume",
            name="first_name",
            field=models.CharField(default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="resume",
            name="last_name",
            field=models.CharField(default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="resume",
            name="phone",
            field=models.CharField(default="", max_length=20, null=True),
        ),
    ]
