# Generated by Django 4.1 on 2023-10-25 18:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mainsite", "0002_alter_employerprofile_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="applicantprofile", name="Birthday",),
        migrations.AddField(
            model_name="applicantprofile",
            name="found_date",
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
        migrations.AlterField(
            model_name="applicantprofile",
            name="address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applicant_addresses",
                to="mainsite.address",
            ),
        ),
    ]
