# Generated by Django 4.1 on 2023-10-26 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mainsite", "0004_rename_found_date_applicantprofile_birth_day_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("job_type", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("description", models.TextField(max_length=2000)),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_location",
                        to="mainsite.address",
                    ),
                ),
                (
                    "applicants",
                    models.ManyToManyField(
                        blank=True,
                        related_name="applied_jobs",
                        to="mainsite.applicantprofile",
                    ),
                ),
                (
                    "employer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="mainsite.employerprofile",
                    ),
                ),
            ],
        ),
    ]
