# Generated by Django 4.1 on 2023-10-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainsite", "0005_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="job_url",
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
