# Generated by Django 4.1 on 2023-11-03 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainsite", "0006_job_job_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="applicants",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="applied_jobs",
                to="mainsite.applicantprofile",
            ),
        ),
    ]
